import matplotlib.pyplot as plt
import numpy as np
x_vals = np.linspace(0, 12, 120)
y_sin = np.sin(x_vals)
y_cos = np.cos(x_vals)
fig, (plot_sin, plot_cos) = plt.subplots(2, 1, figsize=(10, 8))
plot_sin.plot(x_vals, y_sin, label='sin(x)', color='blue', linestyle='-')
plot_sin.set_title('Sine Function')
plot_sin.set_xlabel('x-axis')
plot_sin.set_ylabel('sin(x)')
plot_sin.grid(True)
plot_sin.legend(loc='upper right')
plot_sin.set_xticks(np.arange(0, 13, 1))
plot_sin.set_yticks(np.arange(-1, 1.5, 0.5))
plot_sin.set_xticklabels([f'{i}' for i in range(13)])
plot_sin.set_yticklabels([f'{i:.1f}' for i in np.arange(-1, 1.5, 0.5)])
plot_sin.annotate('Max Value', xy=(np.pi/2, 1), xytext=(np.pi/2+1, 0.8),
                  arrowprops=dict(facecolor='black', shrink=0.05))
plot_cos.plot(x_vals, y_cos, label='cos(x)', color='red', linestyle='--')
plot_cos.set_title('Cosine Function')
plot_cos.set_xlabel('x-axis')
plot_cos.set_ylabel('cos(x)')
plot_cos.grid(True)
plot_cos.legend(loc='upper right')
plot_cos.set_xticks(np.arange(0, 13, 1))
plot_cos.set_yticks(np.arange(-1, 1.5, 0.5))
plot_cos.set_xticklabels([f'{i}' for i in range(13)])
plot_cos.set_yticklabels([f'{i:.1f}' for i in np.arange(-1, 1.5, 0.5)])
plot_cos.annotate('Min Value', xy=(np.pi, -1), xytext=(np.pi+1, -0.8),
                  arrowprops=dict(facecolor='black', shrink=0.05))

plt.tight_layout()
plt.savefig('line_plot_with_annotations.png')
plt.show()
